PITCH_IMAGE_WIDTH = 1050
PITCH_IMAGE_HEIGHT = 680

FIELD_LENGTH_METERS = 105.0
FIELD_WIDTH_METERS = 68.0

SCALE_X = PITCH_IMAGE_WIDTH / FIELD_LENGTH_METERS
SCALE_Y = PITCH_IMAGE_HEIGHT / FIELD_WIDTH_METERS

CENTER_CIRCLE_RADIUS_METERS = 9.15
CENTER_CIRCLE_RADIUS_PIXELS = int(round(CENTER_CIRCLE_RADIUS_METERS * SCALE_X))

PENALTY_BOX_LENGTH_METERS = 16.5
PENALTY_BOX_WIDTH_METERS = 40.32
GOAL_AREA_LENGTH_METERS = 5.5
GOAL_AREA_WIDTH_METERS = 18.32
PENALTY_SPOT_DISTANCE_METERS = 11.0
GOAL_WIDTH_METERS = 7.32